#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Kishin Miakmi <blackgodstone.k@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys

x = 0.0
i = 0

for n in sys.argv[1:]:
    x += float(n)
    i += 1

print(x/i)
