#!/usr/bin/python3

import sys

x = 0.0
i = 0.0

for n in sys.argv[1:]:
    x += float(n)
    i += 1

ave = x/i
data = 0.0

for n in sys.argv[1:]:
    data += (float(n) - ave)*(float(n) - ave)

print(data/i)
